import scrapy

class Product(scrapy.Item):
    cid_no = scrapy.Field()
    nationality = scrapy.Field()
    passport_no = scrapy.Field()
    name = scrapy.Field()
    gender = scrapy.Field()
    date_of_birth = scrapy.Field()
    total_os = scrapy.Field()
    employer_name = scrapy.Field()
    Mobile_Number = scrapy.Field()
    Office_Numbers = scrapy.Field()
    Reference_name_mobile = scrapy.Field()
    Email_ID = scrapy.Field()
    Home_Country_Number = scrapy.Field()
    Designation_Occupation = scrapy.Field()
    Emirates_id = scrapy.Field()
    address = scrapy.Field()
    Residence_number = scrapy.Field()
    scrape_date = scrapy.Field()
    Region = scrapy.Field()

class Product2(scrapy.Item):
    cid_no = scrapy.Field()
    Card_type = scrapy.Field()
    MinimumPayment_Amount = scrapy.Field()
    A_C_no = scrapy.Field()
    Last_statement_date = scrapy.Field()
    Credit_card_limit = scrapy.Field()
    # Days_past_due = scrapy.Field()
    Issue_date = scrapy.Field()
    Next_due_date = scrapy.Field()
    Total_Overdue_amount = scrapy.Field()
    Credit_Shield_Flag_or_Uniq_acno = scrapy.Field()
    Outstanding = scrapy.Field()
    Principal_OS = scrapy.Field()
    Interest_Profit_OS = scrapy.Field()
    Last_payment_date = scrapy.Field()
    Last_payment_amount = scrapy.Field()
    scrape_date = scrapy.Field()
    PROD = scrapy.Field()
    Product_Code = scrapy.Field()
    OD_Limit_Set_Date = scrapy.Field()
    OD_Limit_End_Date = scrapy.Field()
    # Days_Past_Due = scrapy.Field()
    Current_Balance = scrapy.Field()
    Interest_Amount = scrapy.Field()
    Utilisation = scrapy.Field()
    Interest_In_Suspense = scrapy.Field()
    Total_Due = scrapy.Field()
    Expiry_flag = scrapy.Field()
    Current_Bucket_amount = scrapy.Field()

    Bucket_1_amount = scrapy.Field()
    Bucket_2_amount = scrapy.Field()
    Bucket_3_amount = scrapy.Field()
    Bucket_4_amount = scrapy.Field()
    Bucket_5_amount = scrapy.Field()
    Bucket_6_amount = scrapy.Field()
    Bucket_greater_6_amount = scrapy.Field()